// 統一的餐廳資料庫

// 三民校區 (主校區) 的資料
const sanminRestaurants = {
  food: [
    { name: '金大發', type: '火鍋', minPrice: 130, minPriceItem: '昆布豬肉鍋', location: '一中街', googleMapsLink: 'https://maps.google.com/?q=金大發' },
    { name: '花囍家', type: '日式料理', minPrice: 30, minPriceItem: '玉米沙拉兩貫', location: '一中街', googleMapsLink: 'https://maps.google.com/?q=花囍家' },
    { name: '一中飯飯', type: '飯食', minPrice: 120, minPriceItem: '招牌燒肉飯', location: '一中街', googleMapsLink: 'https://maps.google.com/?q=飯飯 一中' },
    { name: '虎福福飯包', type: '飯包', minPrice: 90, minPriceItem: '香煎雞胸肉飯', location: '一中街', googleMapsLink: 'https://maps.google.com/?q=虎福福飯包' },
    { name: '微滷', type: '滷味', minPrice: 110, minPriceItem: '內用低銷110元', location: '一中街', googleMapsLink: '' },
    { name: '偈亭', type: '火鍋', minPrice: 130, minPriceItem: '烏龍麵', location: '一中街', googleMapsLink: 'https://maps.google.com/?q=偈亭 雙十' },
    { name: '三商巧福', type: '牛肉麵', minPrice: 140, minPriceItem: '牛肉炸醬麵 (小)', location: '一中街', googleMapsLink: '' },
    { name: '莊爸炸雞魯肉飯', type: '飯食', minPrice: 50, minPriceItem: '滷肉飯加蛋', location: '一中街', googleMapsLink: '' },
    { name: '頂吉古早味雞肉飯', type: '飯食', minPrice: 40, minPriceItem: '雞肉飯 (小)', location: '一中街', googleMapsLink: '' },
    { name: '鑫吉野', type: '日式料理', minPrice: 80, minPriceItem: '招牌烤肉飯', location: '一中街', googleMapsLink: '' },
    { name: '丸龜製麵', type: '烏龍麵', minPrice: 74, minPriceItem: '釜揚烏龍麵 (中)', location: '一中街', googleMapsLink: '' },
    { name: '丸勝咖哩', type: '咖哩', minPrice: 200, minPriceItem: '有低銷90，外帶訂單享85折優惠', location: '一中街', googleMapsLink: '' },
    { name: 'JT燉飯', type: '燉飯', minPrice: 200, minPriceItem: '燉飯系列', location: '一中街', googleMapsLink: 'https://maps.google.com/?q=JT燉飯' },
    { name: '二口鐵板麵', type: '鐵板麵', minPrice: 70, minPriceItem: '鐵板麵', location: '一中街', googleMapsLink: '' },
    { name: '亞丁尼 一中', type: '義式料理', minPrice: 178, minPriceItem: '義大利麵(主餐都送飲料)', location: '一中街', googleMapsLink: '' },
    { name: '晨家早午餐 一中', type: '早午餐', minPrice: 45, minPriceItem: '起司蛋餅', location: '一中街', googleMapsLink: '' },
    { name: '艾初早午餐 一中太平', type: '早午餐', minPrice: 40, minPriceItem: '火腿蛋吐司', location: '一中街', googleMapsLink: '' },
    { name: 'SUBWAY 台中三民', type: '潛艇堡', minPrice: 125, minPriceItem: '香烤雞肉', location: '三民路', googleMapsLink: '' },
    { name: '肯德基 台中五權餐廳', type: '速食', minPrice: 200, minPriceItem: '肯德基爺爺', location: '五權路', googleMapsLink: '' },
    { name: '漢堡王 一中', type: '速食', minPrice: 100, minPriceItem: '二樓View很好', location: '一中街', googleMapsLink: '' },
    { name: '振興行', type: '麵食', minPrice: 60, minPriceItem: '醬香乾麵(小)', location: '一中街', googleMapsLink: '' },
    { name: '花月嵐 中友', type: '拉麵', minPrice: 200, minPriceItem: '拉麵', location: '中友百貨', googleMapsLink: '' },
    { name: '山西刀削麵食館', type: '麵食', minPrice: 75, minPriceItem: '大滷麵', location: '一中街', googleMapsLink: '' },
    { name: '小象', type: '麵食', minPrice: 90, minPriceItem: '鳳梨蘋果三明治', location: '一中街', googleMapsLink: '' },
    { name: '元春鐵板燒', type: '鐵板燒', minPrice: 80, minPriceItem: '豬肉鐵板燒(學生證有優惠)', location: '一中街', googleMapsLink: '' },
    { name: '忠午飯捲', type: '飯捲', minPrice: 80, minPriceItem: '飯捲便當', location: '一中街', googleMapsLink: '' },
    { name: '抓 蔥抓餅專賣', type: '小吃', minPrice: 40, minPriceItem: '蔥抓餅加蛋', location: '一中街', googleMapsLink: '' },
    { name: '小紅帽烤肉飯', type: '飯食', minPrice: 60, minPriceItem: '烤肉飯捲', location: '一中街', googleMapsLink: '' },
    { name: '食也', type: '飯食', minPrice: 60, minPriceItem: '炒飯', location: '一中街', googleMapsLink: '' },
    { name: '京厚屋 一中', type: '日式料理', minPrice: 258, minPriceItem: '厚切豬排定食', location: '一中街', googleMapsLink: '' },
    { name: '私肉羹', type: '小吃', minPrice: 70, minPriceItem: '香菇肉羹飯', location: '一中街', googleMapsLink: '' },
    { name: '天使雞排', type: '炸物', minPrice: 100, minPriceItem: '雞排', location: '一中街', googleMapsLink: '' },
    { name: '八兩', type: '炸物', minPrice: 100, minPriceItem: '雞排', location: '一中街', googleMapsLink: '' },
    { name: '鍋湯匯 一中', type: '火鍋', minPrice: 160, minPriceItem: '原味豬肉鍋', location: '一中街', googleMapsLink: '' },
    { name: '麥當勞 三民', type: '速食', minPrice: 66, minPriceItem: '+1元多一件到10/7', location: '三民路', googleMapsLink: '' },
    { name: '爭鮮Plus 中友', type: '壽司', minPrice: 200, minPriceItem: '每盤最低40', location: '中友百貨', googleMapsLink: '' },
    { name: '全方位自助餐', type: '自助餐', minPrice: 50, minPriceItem: '依菜色計價', location: '一中街', googleMapsLink: '' },
    { name: '初心手作壽司 一中', type: '壽司', minPrice: 70, minPriceItem: '海苔壽司(8個)', location: '一中街', googleMapsLink: '' },
    { name: '好犀利麻辣鴨血 愛廣場', type: '麻辣鴨血', minPrice: 80, minPriceItem: '麻辣鴨血', location: '愛廣場', googleMapsLink: '' },
    { name: '阿如早餐', type: '早餐', minPrice: 30, minPriceItem: '原味蛋餅', location: '一中街', googleMapsLink: '' },
    { name: '川牛 一中', type: '燒肉丼飯', minPrice: 200, minPriceItem: '丼飯', location: '一中街', googleMapsLink: '' },
    { name: '里奇 健康餐盒 五義店', type: '健康餐盒', minPrice: 105, minPriceItem: '香煎雞排餐盒', location: '五義街', googleMapsLink: '' },
    { name: 'EAT義大利麵', type: '義大利麵', minPrice: 115, minPriceItem: '義大利麵', location: '一中街', googleMapsLink: '' },
    { name: '愛廣場拉麵', type: '拉麵', minPrice: 200, minPriceItem: '拉麵', location: '愛廣場', googleMapsLink: '' },
    { name: '肉蛋吐司紅茶牛奶', type: '早餐', minPrice: 55, minPriceItem: '肉蛋吐司', location: '一中街', googleMapsLink: '' },
    { name: '月光寶盒', type: '義大利麵', minPrice: 100, minPriceItem: '培根義大利麵', location: '一中街', googleMapsLink: '' },
    { name: '晨元元堡早午餐餃館', type: '早午餐', minPrice: 45, minPriceItem: '起司蛋餅', location: '一中街', googleMapsLink: '' },
    { name: '小倆口章魚燒', type: '小吃', minPrice: 45, minPriceItem: '章魚燒', location: '一中街', googleMapsLink: '' },
    { name: '默金 Pasta 義大利面', type: '義大利麵', minPrice: 160, minPriceItem: '義大利麵', location: '一中街', googleMapsLink: '' },
    { name: '諾諾索 Non Lo So 義式料理一中店', type: '義式料理', minPrice: 169, minPriceItem: '義大利麵', location: '一中街', googleMapsLink: '' },
    { name: 'Gray House Living&Pasta 灰房子 義式料理', type: '義式料理', minPrice: 220, minPriceItem: '義大利麵', location: '一中街', googleMapsLink: '' },
    { name: '養機場：中友店', type: '義式料理', minPrice: 170, minPriceItem: '義大利麵/燉飯', location: '中友百貨', googleMapsLink: '' },
    { name: '一郎食堂', type: '韓式料理', minPrice: 100, minPriceItem: '乾拌麵', location: '一中街', googleMapsLink: '' },
    { name: 'Mr.body健身舒肥水煮餐盒 中友店', type: '健康餐盒', minPrice: 110, minPriceItem: '健康餐盒', location: '中友百貨', googleMapsLink: '' },
    { name: '開源社香雞排 一中店', type: '炸物', minPrice: 70, minPriceItem: '香雞排', location: '一中街', googleMapsLink: '' },
    { name: '和記傻瓜麵', type: '麵食', minPrice: 50, minPriceItem: '傻瓜麵', location: '一中街', googleMapsLink: '' },
    { name: '食初', type: '飯食', minPrice: 50, minPriceItem: '炸蛋肉燥飯', location: '一中街', googleMapsLink: '' } ,
    { name: '韓珍饌複合式餐飲', type: '韓式料理', minPrice: 175, minPriceItem: '牛肉食鍋', location: '一中街', googleMapsLink: '' } ,
    { name: '求求辣年糕', type: '韓式料理', minPrice: 110, minPriceItem: '拉麵', location: '一中街', googleMapsLink: '' } ,
    { name: '云居雞白湯製麵所', type: '拉麵', minPrice: 180, minPriceItem: '拉麵', location: '一中街', googleMapsLink: '' } ,
    { name: '大鬍子', type: '小吃', minPrice: 50, minPriceItem: '玉米湯餃', location: '一中街', googleMapsLink: '' } ,
    { name: '聚一波義式料理', type: '義式料理', minPrice: 200, minPriceItem: '聽說備註學生會有優惠，或許值得一試', location: '一中街', googleMapsLink: '' },
    { name: '空氣', type: 'default', minPrice: 1, minPriceItem: '每次教授一直催的時候需要頂樓新鮮氧氣', location: '臺中科技大學', googleMapsLink: 'https://maps.google.com/?q=國立臺中科技大學 資訊與流通學院 頂樓' }
  ],
  drinks: [
    { name: '五十嵐', type: '手搖飲', minPrice: 25, minPriceItem: '四季春青茶 (中)', location: '一中街', googleMapsLink: '' },
    { name: '一沐日', type: '手搖飲', minPrice: 30, minPriceItem: '招牌紅茶 (中)', location: '一中街', googleMapsLink: '' },
    { name: '得正', type: '手搖飲', minPrice: 30, minPriceItem: '春烏龍 (中)', location: '一中街', googleMapsLink: '' },
    { name: '阿里山鐵道紅茶', type: '手搖飲', minPrice: 30, minPriceItem: '紅茶', location: '一中街', googleMapsLink: '' },
    { name: '大茗', type: '手搖飲', minPrice: 30, minPriceItem: '四季春青茶', location: '一中街', googleMapsLink: '' },
    { name: '八曜和茶', type: '手搖飲', minPrice: 35, minPriceItem: '和風茶', location: '一中街', googleMapsLink: '' },
    { name: '先喝道', type: '手搖飲', minPrice: 35, minPriceItem: '英式紅茶', location: '一中街', googleMapsLink: '' },
    { name: '彰北', type: '手搖飲', minPrice: 25, minPriceItem: '紅茶', location: '一中街', googleMapsLink: '' },
    { name: '米克夏', type: '手搖飲', minPrice: 30, minPriceItem: '茉莉原淬綠茶', location: '一中街', googleMapsLink: '' },
    { name: '路上 Camino', type: '手搖飲', minPrice: 30, minPriceItem: '紅茶', location: '一中街', googleMapsLink: '' },
    { name: '艾得咖啡', type: '咖啡', minPrice: 50, minPriceItem: '美式咖啡', location: '一中街', googleMapsLink: '' },
    { name: 'tea top', type: '手搖飲', minPrice: 30, minPriceItem: '高山青', location: '一中街', googleMapsLink: '' },
    { name: '吳家紅茶冰', type: '手搖飲', minPrice: 25, minPriceItem: '紅茶冰', location: '一中街', googleMapsLink: '' },
    { name: '十九茶屋', type: '手搖飲', minPrice: 30, minPriceItem: '日式煎茶', location: '一中街', googleMapsLink: '' },
    { name: '七盞茶', type: '手搖飲', minPrice: 30, minPriceItem: '四季青茶', location: '一中街', googleMapsLink: '' },
    { name: '龜記', type: '手搖飲', minPrice: 30, minPriceItem: '四季春青茶', location: '一中街', googleMapsLink: '' },
    { name: '再睡五分鐘', type: '手搖飲', minPrice: 35, minPriceItem: '棉被日安紅', location: '一中街', googleMapsLink: '' },
    { name: '顏太煮', type: '手搖飲', minPrice: 30, minPriceItem: '煮TEA紅茶', location: '一中街', googleMapsLink: '' },
    { name: '豐味綠豆沙', type: '手搖飲', minPrice: 35, minPriceItem: '綠豆沙', location: '一中街', googleMapsLink: '' },
    { name: '大苑子', type: '手搖飲', minPrice: 30, minPriceItem: '四季春青茶', location: '一中街', googleMapsLink: '' },
    { name: '可不可', type: '手搖飲', minPrice: 30, minPriceItem: '熟成紅茶 (中)', location: '一中街', googleMapsLink: '' },
    { name: '萬波', type: '手搖飲', minPrice: 30, minPriceItem: '島嶼紅茶 (中)', location: '一中街', googleMapsLink: '' },
    { name: '紅濃紅', type: '手搖飲', minPrice: 30, minPriceItem: '紅茶', location: '一中街', googleMapsLink: '' }
  ]
};

// 民生校區的資料 (目前為空，可後續新增)
const minshengRestaurants = {
  food: [
    // { name: '範例店家', type: '飯食', minPrice: 100, minPriceItem: '範例餐點', location: '民生路', googleMapsLink: '' },
  ],
  drinks: [
    // { name: '範例飲料店', type: '手搖飲', minPrice: 50, minPriceItem: '範例飲料', location: '民生路', googleMapsLink: '' },
  ]
};
